export declare const DYNAMO_DB_KEY = "MessageID";
export declare const DYNAMO_DB_SORT = "TimeStamp";
export declare const DYNAMO_DB_POLICY = "AmazonDynamoDBFullAccess";
export declare const CLOUD_WATCH_NAMESPACE = "Voyager_Farhan";
export declare const CLOUD_WATCH_DIMENSION_LATENCY = "Latency";
export declare const CLOUD_WATCH_DIMENSION_AVAILABILITY = "Availability";
export declare const CLOUD_WATCH_POLICY = "CloudWatchFullAccess";
export declare const S3_POLICY = "AmazonS3FullAccess";
export declare const API_GATEWAY_POLICY = "AmazonAPIGatewayInvokeFullAccess";
export declare const MONGO_DB_URI = "mongodb+srv://farhan:skipq2742@cluster0.xxsie.mongodb.net/webHealth?retryWrites=true&w=majority";
export declare const URLS_TO_MONITOR: string[];
